In [12]:
import pandas as pd
from math import sin, cos, atan2, sqrt, pi, radians

In [15]:
df = pd.read_csv("country-capitals.csv")
df.head(15)

,CountryName,CapitalName,CapitalLatitude,CapitalLongitude,CountryCode,ContinentName,Unnamed: 6
0,Somaliland,Hargeisa,9.55,44.050000,NaN,Africa,NaN
1,South Georgia and South Sandwich Islands,King Edward Point,-54.283333,-36.500000,GS,Antarctica,NaN
2,French Southern and Antarctic Lands,Port-aux-Fran챌ais,-49.35,70.216667,TF,Antarctica,NaN
3,Palestine,Jerusalem,31.76666667,35.233333,PS,Asia,NaN
4,Aland Islands,Mariehamn,60.116667,19.900000,AX,Europe,NaN
5,Nauru,Yaren,-0.5477,166.920867,NR,Australia,NaN
6,Saint Martin,Marigot,18.0731,-63.082200,MF,North America,NaN
7,Tokelau,Atafu,-9.166667,-171.833333,TK,Australia,NaN
8,Western Sahara,El-Aai첬n,27.153611,-13.203333,EH,Africa,NaN
9,Afghanistan,Kabul,34.51666667,69.183333,AF,Asia,NaN
10,Albania,Tirana,41.31666667,19.816667,AL,Europe,NaN
11,Algeria,Algiers,36.75,3.050000,DZ,Africa,NaN
12,American Samoa,Pago Pago,-14.26666667,-170.700000,AS,Australia,NaN
13,Andorra,Andorra la Vella,42.5,1.516667,AD,Europe,NaN
14,Angola,Luanda,-8.833333333,13.216667,AO,Africa,NaN

In [16]:
df.tail(15)
#we don't need new index from 0 to 244 -> make CountryName as an index
#we don't need last column, Unnamed (seems to be an error) -> drop the 6th column
#we only need from Afganistan to Zimbabwe -> slice from 9 to 238

,CountryName,CapitalName,CapitalLatitude,CapitalLongitude,CountryCode,ContinentName,Unnamed: 6
230,Vanuatu,Port-Vila,-17.73333333,168.316667,VU,Australia,NaN
231,Venezuela,Caracas,10.48333333,-66.866667,VE,South America,NaN
232,Vietnam,Hanoi,21.03333333,105.850000,VN,Asia,NaN
233,US Virgin Islands,Charlotte Amalie,18.35,-64.933333,VI,North America,NaN
234,Wallis and Futuna,Mata-Utu,-13.95,-171.933333,WF,Australia,NaN
235,Yemen,Sanaa,15.35,44.200000,YE,Asia,NaN
236,Zambia,Lusaka,-15.41666667,28.283333,ZM,Africa,NaN
237,Zimbabwe,Harare,-17.81666667,31.033333,ZW,Africa,NaN
238,US Minor Outlying Islands,Washington,D.C.,38.883333,-77,UM,Australia
239,Antarctica,NaN,0,0.000000,AQ,Antarctica,NaN
240,Northern Cyprus,North Nicosia,35.183333,33.366667,NaN,Europe,NaN
241,Hong Kong,NaN,0,0.000000,HK,Asia,NaN
242,Heard Island and McDonald Islands,NaN,0,0.000000,HM,Antarctica,NaN
243,British Indian Ocean Territory,Diego Garcia,-7.3,72.400000,IO,Africa,NaN
244,Macau,NaN,0,0.000000,MO,Asia,NaN

In [17]:
df = pd.read_csv("country-capitals.csv", index_col="CountryName").drop("Unnamed: 6", axis = 1)
df = df[9:238]
df

,CapitalName,CapitalLatitude,CapitalLongitude,CountryCode,ContinentName
CountryName,,,,,
Afghanistan,Kabul,34.51666667,69.183333,AF,Asia
Albania,Tirana,41.31666667,19.816667,AL,Europe
Algeria,Algiers,36.75,3.050000,DZ,Africa
American Samoa,Pago Pago,-14.26666667,-170.700000,AS,Australia
Andorra,Andorra la Vella,42.5,1.516667,AD,Europe
Angola,Luanda,-8.833333333,13.216667,AO,Africa
Anguilla,The Valley,18.21666667,-63.050000,AI,North America
Antigua and Barbuda,Saint John's,17.11666667,-61.850000,AG,North America
Argentina,Buenos Aires,-34.58333333,-58.666667,AR,South America
Armenia,Yerevan,40.16666667,44.500000,AM,Europe
Aruba,Oranjestad,12.51666667,-70.033333,AW,North America
Australia,Canberra,-35.26666667,149.133333,AU,Australia
Austria,Vienna,48.2,16.366667,AT,Europe
Azerbaijan,Baku,40.38333333,49.866667,AZ,Europe
Bahamas,Nassau,25.08333333,-77.350000,BS,North America
Bahrain,Manama,26.23333333,50.566667,BH,Asia
Bangladesh,Dhaka,23.71666667,90.400000,BD,Asia
Barbados,Bridgetown,13.1,-59.616667,BB,North America
Belarus,Minsk,53.9,27.566667,BY,Europe
Belgium,Brussels,50.83333333,4.333333,BE,Europe
Belize,Belmopan,17.25,-88.766667,BZ,Central America
Benin,Porto-Novo,6.483333333,2.616667,BJ,Africa
Bermuda,Hamilton,32.28333333,-64.783333,BM,North America
Bhutan,Thimphu,27.46666667,89.633333,BT,Asia
Bolivia,La Paz,-16.5,-68.150000,BO,South America
Bosnia and Herzegovina,Sarajevo,43.86666667,18.416667,BA,Europe
Botswana,Gaborone,-24.63333333,25.900000,BW,Africa
Brazil,Brasilia,-15.78333333,-47.916667,BR,South America
British Virgin Islands,Road Town,18.41666667,-64.616667,VG,North America
Brunei Darussalam,Bandar Seri Begawan,4.883333333,114.933333,BN,Asia
...,...,...,...,...,...
Switzerland,Bern,46.91666667,7.466667,CH,Europe
Syria,Damascus,33.5,36.300000,SY,Asia
Taiwan,Taipei,25.03333333,121.516667,TW,Asia
Tajikistan,Dushanbe,38.55,68.766667,TJ,Asia
Tanzania,Dar es Salaam,-6.8,39.283333,TZ,Africa
Thailand,Bangkok,13.75,100.516667,TH,Asia
Timor-Leste,Dili,-8.583333333,125.600000,TL,Asia
Togo,Lome,6.116666667,1.216667,TG,Africa
Tonga,Nuku'alofa,-21.13333333,-175.200000,TO,Australia
Trinidad and Tobago,Port of Spain,10.65,-61.516667,TT,North America
Tunisia,Tunis,36.8,10.183333,TN,Africa
Turkey,Ankara,39.93333333,32.866667,TR,Europe
Turkmenistan,Ashgabat,37.95,58.383333,TM,Asia
Turks and Caicos Islands,Grand Turk,21.46666667,-71.133333,TC,North America
Tuvalu,Funafuti,-8.516666667,179.216667,TV,Australia
Uganda,Kampala,0.316666667,32.550000,UG,Africa
Ukraine,Kyiv,50.43333333,30.516667,UA,Europe
United Arab Emirates,Abu Dhabi,24.46666667,54.366667,AE,Asia
United Kingdom,London,51.5,-0.083333,GB,Europe
United States,Washington,38.883333,-77.000000,US,Central America
Uruguay,Montevideo,-34.85,-56.166667,UY,South America
Uzbekistan,Tashkent,41.31666667,69.250000,UZ,Asia
Vanuatu,Port-Vila,-17.73333333,168.316667,VU,Australia
Venezuela,Caracas,10.48333333,-66.866667,VE,South America
Vietnam,Hanoi,21.03333333,105.850000,VN,Asia
US Virgin Islands,Charlotte Amalie,18.35,-64.933333,VI,North America
Wallis and Futuna,Mata-Utu,-13.95,-171.933333,WF,Australia
Yemen,Sanaa,15.35,44.200000,YE,Asia
Zambia,Lusaka,-15.41666667,28.283333,ZM,Africa
Zimbabwe,Harare,-17.81666667,31.033333,ZW,Africa

### Create a function which takes geolocation (which is a pair of latitude and lontitude) of 2 countries (loc1, loc2)

In [10]:
#loc1 consists of country A's latitude and lontitude
#loc2 consists of country B's latitude and lontitude

In [11]:
def distance(loc1, loc2, R = 6380):
    #change the value into radians
    lat1 = radians(float(loc1[0]))
    lon1 = radians(float(loc1[1]))
    
    lat2 = radians(float(loc2[0]))
    lon2 = radians(float(loc2[1]))
    
    #calculate the distance
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
   
    c = 2 * atan2( sqrt(a), sqrt(1-a) )
    d = R * c # where R is the radius of the Earth
    return d

In [4]:
#create new blank data frame
new_df = pd.DataFrame()

#loop from Afganistan through Zimbabwe
for i in range(len(df)):
    
    #empty list in order to store distance between two countries 
    d = []
    for j in range(len(df)):
        #add each value into the list one by one
        d.append(distance(df.iloc[i][['CapitalLatitude', 'CapitalLongitude']], df.iloc[j][['CapitalLatitude', 'CapitalLongitude']]))
    #after iteration, create a column and add into new_df
    new_df[df.index[i]] = d

In [5]:
#change the name of the index from number to countries' name
new_df.index = df.index

In [6]:
#save to csv
new_df.to_csv("result.csv")